## Copyright (c) 2023, Oracle and/or its affiliates.
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

kind: Service
apiVersion: v1
metadata:
  name: oci-mp-server
  labels:
    app: oci-mp-server
  annotations:
    # service.beta.kubernetes.io/oci-load-balancer-shape: "10Mbps"
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
    service.beta.kubernetes.io/oci-load-balancer-security-list-management-mode: "None"
spec:
  # type: NodePort
  type: LoadBalancer
  selector:
    app: oci-mp-server
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: oci-mp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oci-mp-server
  template:
    metadata:
      labels:
        app: oci-mp-server
        version: v1
    spec:
      containers:
        - name: oci-mp-server
          image: ${REGISTRY_ENDPOINT}/${TENANCY_NAMESPACE}/${HELIDON_APP_NAME}:${BUILDRUN_HASH}
          ports:
            - containerPort: 8080
